nelmio_api_doc:
    documentation:
        info:
            title: BileMo Shop API 
            description: Récupérer les données de vos utilisateurs et vos produits
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
